### ISSUE TITLE
Feature Request: Evidence Attachment

### ISSUE THREAD

**Issue by grf1** [fundakol/behave-xray#20]
I've found this library works really well, the only thing it is missing for me is the 'evidence' attachment for a test scenario execution. 

![image](https://user-images.githubusercontent.com/4109420/224179822-6c57e9ac-4ab2-4880-8969-94f7e27867f1.png)

I think the simplest implementation of this would be an environment variable which points towards a test evidence directory, e.g. _XRAY_EVIDENCE_DIR=/test_evidence_ and all files in this directory would get uploaded. 

This way, it can be left to me (the user) to implement a cleanup of the evidence directory between scenarios, this could be quite straightforward with Behave's after_scenario hook. 

I've had a quick look at the XRay 2.0 API reference, and there looks like a POST method for adding attachments :-) 

Let me know your thoughts, and thanks for making this package - really useful and worked for us straight out the box.

**Comment by fundakol** [comment]
@upvideoio I created PR #21 with solution that allows to attach an evidence. Can you test it?

Here is an example how to use it:
```python
# - FILE: environment.py
from behave.model import Status
from behave_xray import hookimpl
from behave_xray.evidence import text

@hookimpl
def scenario_xray_result(result, scenario):
    if scenario.status == Status.failed:
        result.evidences.append(text(data='This is scenario evidence', filename=f'{scenario.name}.txt'))
```

**Comment by grf1** [comment]
Thanks @fundakol, I'm currently testing this and will get back to you soon

**Comment by grf1** [comment]
Hi @fundakol, I'm getting the following error (using a non-cloud hosted JIRA) 

`Error message from server: Error instantiating bean. Field(s) tests -> evidences -> ContentType do not follow the correct format.`

In my environment.py, using the results.evidences.append method, the filenames I've tried are either .jpeg, .jpg or .txt and all of them have done the same thing.

**Comment by grf1** [comment]
I believe I've found the issue mentioned above, the field for 'contentType' is currently written as 'ContentType'. 

I've reviewed the Xray API docs, and made a change locally to your code and it works absolutely fine when using the camel case version. 

<img width="961" alt="Screenshot 2023-04-25 at 13 48 49" src="https://user-images.githubusercontent.com/4109420/234281698-169b1f43-b1c8-4b0a-9a3a-a7ae8e636758.png">

My only other feedback would be, if you can add the content types for CSV files, JSON files, and ZIP files please :-) Although I can do this locally too, I think others may find it useful, for example a lot of logs are either CSV or JSON and its often easier to bundle them into a ZIP to save some space. 

Thanks for developing this additional feature!

**Comment by fundakol** [comment]
@grf1 many thanks for the feedback, I will update the PR. 
Did you find a list of supported contentType? Can you share it?

I guess CSV and JSON are plain text and contentType should be `plain/text`. I am wondering what should be for zip file.

**Comment by grf1** [comment]
@fundakol hopefully this helps: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types 

Will look out for the updated package on pypi! thanks again 👍

**Comment by grf1** [comment]
@fundakol  just one thing I notice in that latest commit, although the new content types are there (thank you) the functions to use them aren't.. is this intended?

**Comment by fundakol** [comment]
Fixed.
