### ISSUE TITLE
Support for Xray-managed cucumber tests?

### ISSUE THREAD

**Issue by kconkas** [fundakol/behave-xray#9]
Xray can manage tests in Cucumber format (see the Jira based Cucumber workflow chapter in the [documentation](https://docs.getxray.app/pages/viewpage.action?pageId=62267221) and, when exporting them as feature files, adds tags that correspond to Xray scenarios and preconditions.

For example, a test MYPROJ-1604 with precondition PRECOND_MYPROJ-1703 after export becomes:
```
Feature: Calculator can sum positive integers

	Background:
		#@PRECOND_MYPROJ-1703
		Given I have a calculator

	#My issue comments
	@TEST_MYPROJ-1604 @positive
	Scenario Outline: Calculator can sum positive integers
		When I use my calculator to calculate the sum of <first_integer> and <second_integer>
		Then I see the result is <result>
		Examples:
		    | first_integer | second_integer | result |
		    | 1             | 1              | 2      |
		    | 100           | 5              | 103    |

```

It would be really neat to be able to run behave on these files and have them seamlessly import into Xray as that'd allow out of the box Xray integration using the recommended workflow.

**Comment by fundakol** [comment]
If I understand you correct you want to recognize tag like `@TEST_MYPROJ-1604` as test case ID, am I wrong? 

According to the Xray documentation it is possible to export JSON result generated by behave to Xray. Xray should be able to map IDs from tags to proper test cases. Did you try this solution?
https://docs.getxray.app/display/XRAY/Import+Execution+Results+-+REST#ImportExecutionResultsREST-BehaveJSONresults

**Comment by kconkas** [comment]
@fundakol yes, I did, this is how I got generated the above feature file. If you are open to contributions I would be happy to send you a small PR to implement this.

**Comment by fundakol** [comment]
You can implement this if you wish, I am open for any contribution. 
How you want to implement this? Do you want to parse tags with test id or just to generate behave report and send it to Xray? Second option seems to be easier one.

**Comment by kconkas** [comment]
@fundakol I already have a working option to generate the behave report and import it separately but what attracts me to your library is that it uploads the results automatically and uses the native Xray import format (rather than cucumber, which I currently use) so this looks to me like a better long-term solution. 

You've got almost everything ready for what I'm proposing here, the only work needed doing is handing the Xray-exported jira issue tags in https://github.com/fundakol/behave-xray/blob/master/src/behave_xray/helper.py#L23 and that's what I'm proposing to do.

**Comment by fundakol** [comment]
Looks good to me. You can create PR with your implementation.

**Comment by kconkas** [comment]
@fundakol in https://github.com/fundakol/behave-xray/blob/master/src/behave_xray/formatter.py#L96 you ignore features with no tags, presumably because you always expect the features to have `jira.test_plan` tag. Features exported from Xray cucumber tests won't have any such tags by default. Do you see any issues if I were to remove this check?

**Comment by kconkas** [comment]
Since the associated PR has been merged to master, I am happy to close this issue.
